export const environment = {
    production: false,
    apiKey:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MzI5YThkYS05OTBjLTQyYTAtYjkzMy01NzkwMzEwZTQ0MzMiLCJlbWFpbCI6ImJnY0BleGFtcGxlLmNvbSIsImdpdmVuX25hbWUiOiJiZ2MiLCJuYmYiOjE2OTY1NTgwMjMsImV4cCI6MTY5NjU4NjgyMywiaWF0IjoxNjk2NTU4MDIzLCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.HhuyImzmOk0RWc79V3MOnICtN3s9ZBBde-C7IZ7uN7Y',
  };