export const environment = {
    production: true,
    apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MzI5YThkYS05OTBjLTQyYTAtYjkzMy01NzkwMzEwZTQ0MzMiLCJlbWFpbCI6ImJnY0BleGFtcGxlLmNvbSIsImdpdmVuX25hbWUiOiJiZ2MiLCJuYmYiOjE2OTY0NjMzMjcsImV4cCI6MTY5NjQ5MjEyNywiaWF0IjoxNjk2NDYzMzI3LCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.WI3S2pGF_NsRexmBQkR_fuNhE81-yD3AywoNiipFbJ0',
  };