export const environment = {
    production: false,
    apiKey:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MzI5YThkYS05OTBjLTQyYTAtYjkzMy01NzkwMzEwZTQ0MzMiLCJlbWFpbCI6ImJnY0BleGFtcGxlLmNvbSIsImdpdmVuX25hbWUiOiJiZ2MiLCJuYmYiOjE2OTYzNTc0ODUsImV4cCI6MTY5NjM4NjI4NSwiaWF0IjoxNjk2MzU3NDg1LCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.2qLLTD7sqr21_oBtrkivZnCUEs9BCERQfOQjc6LEUm0',
  };