export const environment = {
    production: false,
    apiKey:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MzI5YThkYS05OTBjLTQyYTAtYjkzMy01NzkwMzEwZTQ0MzMiLCJlbWFpbCI6ImJnY0BleGFtcGxlLmNvbSIsImdpdmVuX25hbWUiOiJiZ2MiLCJuYmYiOjE2OTY2MTExMDIsImV4cCI6MTY5NjYzOTkwMiwiaWF0IjoxNjk2NjExMTAyLCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.qC0AS2cLkEi-KGAKcKZfrg1EyEITn68z7ah-fbf8H8Y',
  };